import 'package:isar/isar.dart';
part 'barcode_batch.g.dart';

///This stores details about barcodes generated by the user.
/// - Time of creation.
/// - Size of the barcodes.
/// - The number of the first barcode.
/// - The number of the last barcode.
/// - Imported ?
@Collection()
@Name("BarcodeBatch")
class BarcodeBatch {
  Id id = Isar.autoIncrement;

  //Generation Time.
  @Name("timestamp")
  late int timestamp;

  ///Side length (mm)
  @Name("width")
  late double width;

  ///Side length (mm)
  @Name("height")
  late double height;

  ///Barcode range start.
  @Name("rangeStart")
  late int rangeStart;

  ///Barcode range end.
  @Name("rangeEnd")
  late int rangeEnd;

  ///Barcode Size.
  @Name("imported")
  late bool imported;

  @override
  String toString() {
    return '\ntimestamp: $timestamp, h: $height, w: $width';
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'timestamp': timestamp,
        'width': width,
        'height': height,
        'rangeStart': rangeStart,
        'rangeEnd': rangeEnd,
        'imported': imported,
      };

  BarcodeBatch fromJson(Map<String, dynamic> json) {
    return BarcodeBatch()
      ..id = json['id']
      ..timestamp = json['timestamp'] as int
      ..width = json['width'] as double
      ..height = json['height'] as double
      ..rangeStart = json['rangeStart'] as int
      ..rangeEnd = json['rangeEnd'] as int
      ..imported = json['imported'] as bool;
  }

  @override
  int get hashCode => super.hashCode;
}
